CREATE OR REPLACE FUNCTION is_truthy(JSON) RETURNS BOOLEAN AS
$$ SELECT $1::text NOT IN ('{}', '0', '""', '[]'); $$
LANGUAGE SQL IMMUTABLE
RETURNS NULL ON NULL INPUT;


CREATE OR REPLACE FUNCTION is_truthy(JSONB) RETURNS BOOLEAN AS
$$ SELECT $1::text NOT IN ('{}', '0', '""', '[]'); $$
LANGUAGE SQL IMMUTABLE
RETURNS NULL ON NULL INPUT;


DROP CAST IF EXISTS (JSON AS BOOLEAN);
CREATE CAST (JSON AS BOOLEAN) WITH FUNCTION is_truthy(JSON) AS ASSIGNMENT;
DROP CAST IF EXISTS (JSONB AS BOOLEAN);
CREATE CAST (JSONB AS BOOLEAN) WITH FUNCTION is_truthy(JSONB) AS ASSIGNMENT;
